# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34beabc0c0509c0ba9a667e9ecfa151cd407257457f3caef1e4c24249e4c000d772a17a6691bd4b10e993c0ab0119dc25dc09a37c94d31dee70b29af15b7639a

test:
  secret_key_base: 10426423c3f63c420f999e656e19b1f50a9d03a4560c0c5c63093911a2ea9e672aeb15d04b3d69559bea675f530f8ba62f61ae33d97eeb21549d4491b596ab07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
